# Generated by Django 4.2 on 2023-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
